spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /console
  batch:
    job:
      enabled: false
server:
  port: 8081